---
- hosts: webservers
  remote_user: ubuntu
  roles:
    - role: apache
    - role: java8

- hosts: jenkinserver
  remote_user: pratik
  pre_tasks:
    - name: "Check packages info"
      package_facts:
        manager: "auto"
  roles:
    - role: apache
    - role: java8
    - role: jenkins
      when: "'jenkins' not in ansible_facts.packages"
...
